VISION_PROMPT = (
    "Identify every food item visible in this image. "
    "For each item, call the record_identified_foods tool with the following fields: "
    "name (string — the food name), "
    "estimated_grams (float greater than 0 — the estimated portion weight in grams), "
    "confidence (float between 0.0 and 1.0 — how confident you are in the identification). "
    "If no food items are present, call the tool with an empty items list."
)

TEXT_PROMPT = (
    "Identify every food item described in the text below. "
    "For each item, call the record_identified_foods tool with the following fields: "
    "name (string — the food name), "
    "estimated_grams (float greater than 0 — the estimated portion weight in grams), "
    "confidence (float between 0.0 and 1.0 — how confident you are in the identification). "
    "If no food items are described, call the tool with an empty items list.\n\n"
    "Quantity interpretation rules:\n"
    "- Colloquial Spanish quantities: 'un cacho' or 'un trozo' ≈ 30 g, 'un puñado' ≈ 30 g, "
    "'un chorro' ≈ 15 ml (use 15 g), 'una pizca' ≈ 2 g, 'un chorrito' ≈ 10 ml.\n"
    "- Implicit Spanish food units: 'un yogur' ≈ 125 g, 'un plátano' ≈ 120 g, "
    "'una manzana' ≈ 150 g, 'una naranja' ≈ 150 g, 'un café' ≈ 30 ml (use 30 g), "
    "'un pocillo' ≈ 30 ml, 'una taza' ≈ 240 ml, 'un vaso' ≈ 200 ml, "
    "'una cucharada' ≈ 15 g, 'una cucharadita' ≈ 5 g.\n"
    "- When no quantity is stated, infer a typical single-serving portion.\n\n"
    "Compound food rules:\n"
    "- Split compound descriptions into individual food items. "
    "For example, 'arroz con pollo y ensalada' → three separate items: arroz, pollo, ensalada. "
    "'Tostadas con mantequilla y mermelada' → tostadas, mantequilla, mermelada.\n"
    "- Assign a reasonable portion weight to each component independently."
)
